[package]
name = "ntex-mqtt"
version = "0.3.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "MQTT v3.1.1 Client/Server framework"
documentation = "https://docs.rs/ntex-mqtt"
repository = "https://github.com/ntex-rs/ntex-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
ntex = "0.1.1"
ntex-mqtt-codec = "0.3.0"

derive_more = "0.99.2"
bytes = "0.5.3"
either = "1.5.2"
futures = "0.3.1"
pin-project = "0.4.6"
log = "0.4"
bytestring = "0.1.5"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6"

[patch.crates-io]
ntex-mqtt = { path = "." }
ntex-mqtt-codec = { path = "codec" }

ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-rt = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-codec = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-router = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-macros = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-web-macros = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-service = { git = "https://github.com/ntex-rs/ntex.git" }
