[package]
name = "actix-mqtt"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "MQTT v3.1 Server framework"
documentation = "https://docs.rs/actix-mqtt"
repository = "https://github.com/actix/actix-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
mqtt-codec = "0.1.0"
actix-codec = "0.1.2"
actix-service = "0.4.1"
actix-utils = "0.4.2"
actix-router = "0.1.5"
actix-server-config = "0.1.1"
actix-ioframe = { git="https://github.com/actix/actix-net.git" }
#actix-ioframe = { path = "../../actix/actix-net/actix-ioframe" }

derive_more = "0.15.0"
bytes = "0.4"
either = "1.5.2"
futures = "0.1.25"
log = "0.4"
string = "0.2.0"
serde = "1.0"
serde_json = "1.0"
tokio-current-thread = "0.1.4"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6"
actix-connect = "0.2.0"
actix-server = "0.5.1"
actix-test-server = "0.2.2"
tokio-tcp = "0.1"

[patch.crates-io]
actix-mqtt = { path = "." }
mqtt-codec = { path = "codec" }
