[package]
name = "actix-mqtt"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "MQTT v3.1 Server framework"
documentation = "https://docs.rs/actix-mqtt"
repository = "https://github.com/actix/actix-mqtt.git"
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
mqtt-codec = { git = "https://github.com/fafhrd91/mqtt-codec.git" }
# mqtt-codec = { path = "../mqtt-codec" }

actix-codec = "0.1.0"
#actix-service = "0.2.2"
#actix-utils = "0.2.2"
#actix-service = { path = "../../actix/actix-net/actix-service" }
#actix-utils = { path = "../../actix/actix-net/actix-utils" }
actix-service = { git = "https://github.com/actix/actix-net.git" }
actix-utils = { git = "https://github.com/actix/actix-net.git" }
actix-router = { git = "https://github.com/actix/actix-net.git" }
derive_more = "0.14"
bytes = "0.4"
futures = "0.1"
either = "1.5.1"
log = "0.4"
string = "0.1.3"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
env_logger = "0.6"
#actix-server = "0.2.1"
#actix-server = { path = "../../actix/actix-net/actix-server" }
actix-server = { git = "https://github.com/actix/actix-net.git" }
actix-test-server = { git = "https://github.com/actix/actix-net.git" }
