[package]
name = "mqtt"
version = "0.1.2"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "MQTT protocol v3.1.1 implementation"
documentation = "https://docs.rs/mqtt"
homepage = "https://github.com/flier/rust-mqtt"
repository = "https://github.com/flier/rust-mqtt.git"
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "mqtt"

[dependencies]
log = "0.4"
bitflags = "1.0"
rand = "0.3"
byteorder = "1.0"
slab = "0.4"
bytes = "0.4"
string = "0.1.3"
futures = "0.1.24"
tokio-codec = "0.1"

[dev-dependencies]
env_logger = "^0.3"
clap = "^2"
