[package]
name = "ntex-mqtt"
version = "0.6.0-b.1"
authors = ["ntex contributors <team@ntex.rs>"]
description = "MQTT Client/Server framework for v5 and v3.1.1 protocols"
documentation = "https://docs.rs/ntex-mqtt"
repository = "https://github.com/ntex-rs/ntex-mqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[dependencies]
ntex = "0.3.1"
ntex-router = "0.4.0"
bitflags = "1.2.1"
bytes = "1.0"
bytestring = "1.0"
derive_more = "0.99.11"
either = "1.6.1"
futures = "0.3.13"
ahash = "0.7.0"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
pin-project-lite = "0.2.4"

[dev-dependencies]
env_logger = "0.8"

rustls = "0.19"
tokio-rustls = "0.22.0"
openssl = "0.10"
tokio-openssl = "0.6.1"

ntex = { version = "0.3.1", features = ["rustls", "openssl"] }
